[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
via_ir = false

# Use FOUNDRY_PROFILE=layer2 when compiling or deploying to Taiko L2
[profile.layer2]
evm_version = "shanghai"

# Required for OpenZeppelin Upgrades plugin
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
taiko-mainnet = "https://rpc.mainnet.taiko.xyz"
taiko-hoodi = "https://rpc.hoodi.taiko.xyz"
ethereum-mainnet = "${ETH_RPC_URL}"
ethereum-hoodi = "${HOODI_RPC_URL}"

[etherscan]
taiko-mainnet = { key = "${TAIKOSCAN_API_KEY}", url = "https://api.taikoscan.io/api", chain = 167000 }
taiko-hoodi = { key = "${TAIKOSCAN_API_KEY}", url = "https://api-hoodi.taikoscan.io/api", chain = 167013 }
ethereum-mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 1 }
ethereum-hoodi = { key = "${ETHERSCAN_API_KEY}", chain = 560048 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 200

[invariant]
runs = 256
depth = 15
